# Make sure to check the documentation at https://goreleaser.com

# The lines below are called `modelines`. See `:help modeline`
# Feel free to remove those if you don't want/need to use them.
# yaml-language-server: $schema=https://goreleaser.com/static/schema.json
# vim: set ts=2 sw=2 tw=0 fo=cnqoj

# More examples at https://github.com/goreleaser/goreleaser/blob/main/.goreleaser.yaml

version: 2

before:
  hooks:
    - go mod tidy
    # you may remove this if you don't need go generate
    # - go generate ./...
    - /bin/sh -c "set -e; mkdir -p completions; go run cmd/kefw2/kefw2.go completion bash > completions/kefw2.bash; go run cmd/kefw2/kefw2.go completion zsh > completions/kefw2.zsh; go run cmd/kefw2/kefw2.go completion fish > completions/kefw2.fish; go run cmd/kefw2/kefw2.go completion powershell > completions/kefw2.ps1"

builds:
  - id: kefw2
    main: ./cmd/kefw2/kefw2.go
    binary: kefw2
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64
    goarm:
      - "7"
    # ignore:
    #   - goos: windows
    #     goarch: arm
    mod_timestamp: "{{ .CommitTimestamp }}"
    flags:
      - -trimpath
    ldflags:
      - -s -w -X main.version={{.Version}} -X main.commit={{.Commit}} -X main.date={{ .CommitDate }} -X main.builtBy=goreleaser -X main.treeState={{ .IsGitDirty }}
      
archives:
  - formats: [ tar.gz ]
    # this name template makes the OS and Arch compatible with the results of `uname`.
    name_template: >-
      {{ .ProjectName }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end }}
    # use zip for windows archives
    format_overrides:
      - goos: windows
        format: zip
    files:
      - README.md
      - LICENSE
      - completions/*

brews:
  - name: kefw2
    goarm: 7
    commit_author:
      name: Jens Hilligsøe
      email: github@hilli.dk
    commit_msg_template: "Brew formula update for {{ .ProjectName }} version {{ .Tag }}"
    homepage: "https://github.com/hilli/go-kef-w2"
    description: "Command for handling KEF W2 platform speakers (LSX Wireless II (LT)/LS50 Wireless II/LS60 Wireless)"
    license: "MIT"
    url_template: "https://github.com/hilli/go-kef-w2/releases/download/{{ .Tag }}/{{ .ArtifactName }}"
    skip_upload: false
    repository:
      owner: hilli
      name: homebrew-tap
      branch: release-go-kef-w2-{{.Tag}}
      pull_request:
        enabled: true
        draft: false
    extra_install: |-
      bash_completion.install "completions/kefw2.bash" => "kefw2"
      zsh_completion.install "completions/kefw2.zsh" => "_kefw2"
      fish_completion.install "completions/kefw2.fish"

scoops:
  - repository:
      owner: hilli
      name: scoop-bucket
    homepage: https://github.com/hilli/go-kef-w2
    description: Command for handling KEF W2 platform speakers (LSX Wireless II (LT)/LS50 Wireless II/LS60 Wireless)
    license: MIT
    post_install:
      - Write-Host 'Running postinstall command'
      - if(!(Test-Path $PROFILE.CurrentUserCurrentHost -PathType Leaf)) { New-Item -Path $PROFILE.CurrentUserCurrentHost -ItemType file -Force }
      - $scoopPrefix = $(scoop prefix go-kef-w2)
      - $profilecontent = Get-Content $PROFILE.CurrentUserCurrentHost
      - if(-not($profilecontent | select-string -pattern "$scoopPrefix\completions\kefw2.ps1" -CaseSensitive -SimpleMatch)) { Add-Content -Path $PROFILE.CurrentUserCurrentHost -Value ". $scoopPrefix\completions\kefw2.ps1" }

nfpms:
  - file_name_template: "{{ .ConventionalFileName }}"
    id: packages
    homepage: https://github.com/hilli/go-kef-w2
    description: |-
      Command for handling KEF W2 platform speakers (LSX Wireless II (LT)/LS50 Wireless II/LS60 Wireless)
    maintainer: Jens Hilligsøe <kefw2@hilli.dk>
    license: MIT
    vendor: Jens Hilligsøe
    bindir: /usr/bin
    section: utils
    contents:
      - src: ./completions/kefw2.bash
        dst: /usr/share/bash-completion/completions/kefw2
        file_info:
          mode: 0644
      - src: ./completions/kefw2.fish
        dst: /usr/share/fish/vendor_completions.d/kefw2.fish
        file_info:
          mode: 0644
      - src: ./completions/kefw2.zsh
        dst: /usr/share/zsh/vendor-completions/_kefw2
        file_info:
          mode: 0644
      - src: ./LICENSE
        dst: /usr/share/doc/kefw2/copyright
        file_info:
          mode: 0644
    formats:
      - apk
      - deb
      - rpm
      - archlinux
    deb:
      lintian_overrides:
        - statically-linked-binary
        - changelog-file-missing-in-native-package

announce:
  mastodon:
    enabled: true
    # Default: '{{ .ProjectName }} {{ .Tag }} is out! Check it out at {{ .ReleaseURL }}'
    # message_template: 'kefw2 {{.Tag}} is out! Get it at {{.ReleaseURL}}'
    server: https://mastodon.social

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
