# This is a Taskfile. See https://taskfile.dev
# `brew install go-task` to install task runner
# `task --list` to list all tasks
# `task <taskname>` to run a task

version: '3'

tasks:
  setup:
    desc: Install dependencies
    cmds:
      - brew install vhs

  build:
    desc: Build binaries
    cmds:
      - go build -o bin/kefw2 cmd/kefw2/kefw2.go

includes:
  docs:
    taskfile: ./docs/Taskfile.yaml
    dir: ./docs
