# This is a Taskfile. See https://taskfile.dev
# `brew install go-task` to install task runner or `go install github.com/go-task/task/v3/cmd/task@latest`
# `task --list` to list all tasks
# `task <taskname>` to run a task

version: '3'

tasks:
  setup:
    desc: Install dependencies
    run: once
    cmds:
      - brew install vhs

  build:
    desc: Build binaries
    cmds:
      - go build -ldflags="-X github.com/hilli/go-kef-w2/cmd.Version={{.GIT_COMMIT}}" -o bin/kefw2 cmd/kefw2/kefw2.go
    alias: [b]
    sources:
      - cmd/kefw2/**/*.go
      - kefw2/*.go
    generates:
      - bin/kefw2
    vars:
      GIT_COMMIT:
        sh: git log -n 1 --format=%h

  complete:
    desc: Generate bash/zsh completion script
    cmds:
      - bin/kefw2 completion bash > /usr/local/share/bash-completion/completions/kefw2
      - bin/kefw2 completion zsh > /usr/local/share/zsh-completions/_kefw2
    sources:
      - cmd/kefw2/**/*.go
      - kefw2/*.go
    generates:
      - /usr/local/share/bash-completion/completions/kefw2
      - /usr/local/share/zsh-completions/_kefw2

includes:
  docs:
    taskfile: ./docs/Taskfile.yaml
    dir: ./docs
