version:  '3'

tasks:
  setup:
    desc: Install dependencies
    run: once
    cmds:
      - go install fyne.io/fyne/v2/cmd/fyne@latest
      - go install github.com/fyne-io/fyne-cross@latest

  build-all: # See https://developer.fyne.io/started/cross-compiling
   desc: Build for all platforms
   cmds:
    - fyne-cross linux -arch=amd64,arm64
    - fyne-cross windows -app-id com.github.hilli.KeFW2Player
    - fyne-cross darwin -arch=amd64,arm64
