version: '3'
tasks:
  setup:
    desc: Install dependencies
    run: once
    cmds:
      - brew install vhs

  record:
    desc: Record kefw2.tape actions to docs/kefw2.gif (requires vhs, Music.app and JXA)
    deps:
      - setup
    platforms: [darwin]
    cmds:
      - rm -f ~/.config/kefw2/kefw2.yaml
      - vhs kefw2.tape
    preconditions:
      - test -f ../bin/kefw2
      - which vhs
